version: '3'
services:
  flat-agent:
    build: .
    image: flat-agent
    environment:
      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: 587
      EMAIL_USER: mail@example.com
      EMAIL_PASSWORD: password123
      DEFAULT_FROM_EMAIL: mail@example.com
      DEFAULT_TO_EMAIL: mail@example.com
      SEARCH_URL: https://www.immobilienscout24.de/Suche/S-2/Wohnung-Miete/Hamburg/Hamburg/-/-/-/EURO--1500,00
    volumes:
      - /docker-data/flatagent/data:/root/flat_agent/data
    container_name: flat-agent
    restart: unless-stopped
